project:
  type: website

website:
  title: "BiOSCape Terrestrial Data"
  navbar:
    left:
      - href: Vegplot_Rarefaction.qmd
        text: Rarefaction
      - href: botanist_photo_processing.qmd
        text: Botanist Photo Processing

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

