<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jasper Slingsby, Ross Turner, Douglas Euston-Brown, Greg Nicolson, Steven Molteno, Stuart Hall, Paul Emms, Henry. A. Frye, Phillip. A. Townsend, Anabelle Cardoso, Erin Hestir, Brian Maitner, Adam M. Wilson">
<meta name="dcterms.date" content="2026-10-07">

<title>BioSCape Vegetation Plots, Cape Floristic Region, South Africa, 2023 – BioSCape Terrestrial Data</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">BioSCape Terrestrial Data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../Vegplot_Rarefaction.html"> 
<span class="menu-text">Rarefaction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../botanist_photo_processing.html"> 
<span class="menu-text">Botanist Photo Processing</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../ornl_daac/vegplot_readme.html" aria-current="page"> 
<span class="menu-text">Data Release v1</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#dataset-overview" id="toc-dataset-overview" class="nav-link" data-scroll-target="#dataset-overview">Dataset overview</a></li>
  <li><a href="#dataset-characteristics" id="toc-dataset-characteristics" class="nav-link" data-scroll-target="#dataset-characteristics">Dataset characteristics</a>
  <ul class="collapse">
  <li><a href="#file-naming-convention" id="toc-file-naming-convention" class="nav-link" data-scroll-target="#file-naming-convention">File naming convention</a></li>
  <li><a href="#file-descriptions" id="toc-file-descriptions" class="nav-link" data-scroll-target="#file-descriptions">File descriptions</a></li>
  <li><a href="#data-file-properties" id="toc-data-file-properties" class="nav-link" data-scroll-target="#data-file-properties">Data file properties</a></li>
  <li><a href="#data-details" id="toc-data-details" class="nav-link" data-scroll-target="#data-details">Data details</a></li>
  </ul></li>
  <li><a href="#application-and-derivation" id="toc-application-and-derivation" class="nav-link" data-scroll-target="#application-and-derivation">Application and derivation</a></li>
  <li><a href="#quality-assessment" id="toc-quality-assessment" class="nav-link" data-scroll-target="#quality-assessment">Quality assessment</a></li>
  <li><a href="#data-acquisition-materials-and-methods" id="toc-data-acquisition-materials-and-methods" class="nav-link" data-scroll-target="#data-acquisition-materials-and-methods">Data acquisition, materials, and methods</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#dataset-revisions" id="toc-dataset-revisions" class="nav-link" data-scroll-target="#dataset-revisions">Dataset revisions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BioSCape Vegetation Plots, Cape Floristic Region, South Africa, 2023</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jasper Slingsby, Ross Turner, Douglas Euston-Brown, Greg Nicolson, Steven Molteno, Stuart Hall, Paul Emms, Henry. A. Frye, Phillip. A. Townsend, Anabelle Cardoso, Erin Hestir, Brian Maitner, Adam M. Wilson </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p><strong>Dataset title:</strong> BioSCape Vegetation Plots, Cape Floristic Region, South Africa, 2023</p>
<p><strong>Summary:</strong> Vegetation composition and cover at 189 field plots in the Greater Cape Floristic Region of South Africa, collected for the Biodiversity Survey of the Cape (BioSCape). Each plot was surveyed once between 2023-05-03 and 2023-11-01 and divided into four quadrants (NE, NW, SE, SW). The product reports quadrant-level and plot-level fractional cover of bare soil, bare rock, dead vegetation, and live vegetation, together with species-level percent cover, stem counts, and canopy diameter for 709 species. All species with at least 5% cover were included in the dataset, plus additional species where needed to make up 80% of the total cover. The data were collected in the field by botanists. Plot-center coordinates are in the companion spatial file.</p>
</section>
<section id="dataset-overview" class="level2">
<h2 class="anchored" data-anchor-id="dataset-overview">Dataset overview</h2>
<p>Project: Biodiversity Survey of the Cape (BioSCape), an integrated field and airborne campaign in the Greater Cape Floristic Region (Cardoso et al.&nbsp;2025).</p>
<p><strong>Related publication:</strong></p>
<p>Cardoso, A.W., E.L. Hestir, J.A. Slingsby, C.J. Forbes, G.R. Moncrieff, W. Turner, A.L. Skowno, J. Nesslage, P.G. Brodrick, K.D. Gaddis, and A.M. Wilson. 2025. The biodiversity survey of the Cape (BioSCape), integrating remote sensing with biodiversity science. <em>npj Biodiversity</em> 4:2. <a href="https://doi.org/10.1038/s44185-024-00071-5" class="uri">https://doi.org/10.1038/s44185-024-00071-5</a></p>
<p><strong>Related datasets:</strong></p>
<ul>
<li>Fitzpatrick, M.C., D. Spalink, A.J. Elmore, J. Measey, and S. Kritzinger-Klopper. 2026. BioSCape: Vegetation Composition at Plots with Woody Invasives, CFR, South Africa. ORNL DAAC. <a href="https://doi.org/10.3334/ORNLDAAC/2511" class="uri">https://doi.org/10.3334/ORNLDAAC/2511</a>. Those plots follow this survey protocol and were placed near these plots, in vegetation that also contained woody invasive cover.</li>
<li>Slimp, M., J. Malindi, R. Meyer, A. Cunningham, J. Rourke, M. Hayden, A. Hargey, J. Nesslage, S. Johnson, M. Rossi, and N. Stavros. 2025. BioSCape Vegetation Surveys Berg and Eerste River Catchments, South Africa, 2022–2023. ORNL DAAC. <a href="https://doi.org/10.3334/ORNLDAAC/2425" class="uri">https://doi.org/10.3334/ORNLDAAC/2425</a>. Same campaign, different sites and some different measurements.</li>
</ul>
<p><strong>Acknowledgments:</strong> Cardoso et al.&nbsp;(2025) report NASA award 80NSSC21K0086 to A.M. Wilson and E.L. Hestir for the U.S. components of BioSCape, and National Research Foundation grant 142438 to J.A. Slingsby.</p>
</section>
<section id="dataset-characteristics" class="level2">
<h2 class="anchored" data-anchor-id="dataset-characteristics">Dataset characteristics</h2>
<p><strong>Spatial coverage:</strong> Greater Cape Floristic Region, Western Cape and Eastern Cape, South Africa. Site codes in the plot summary: agulhas, anysberg, bainskloof, bavianskloof, bontebok, capepoint, cederberg, dehoop, franschoekpass, gardenroute, grootbos, grootwinterhoek, Hawequas, houwhoekpass, kogelberg, langeberg, outeniqua, rooiberg, swartberg, viljoenspass, vrolijkheid, westcoast.</p>
<p><strong>Spatial resolution:</strong> One circular vegetation plot with a diameter of 10m at each location, subdivided into four quadrants.</p>
<p><strong>Temporal coverage:</strong> 2023-05-03 00:00:00 to 2023-11-01 23:59:59 UTC. <code>date</code> in the quadrat summary is the survey calendar date. Each plot has one date.</p>
<p><strong>Temporal resolution:</strong> One sample per plot.</p>
<p><strong>Study area:</strong> Bounding box of the <code>plot_centers</code> layer in bioscape_veg_spatial_v20261002.gpkg, WGS 84 decimal degrees.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Site</th>
<th style="text-align: left;">Westernmost longitude</th>
<th style="text-align: left;">Easternmost longitude</th>
<th style="text-align: left;">Northernmost latitude</th>
<th style="text-align: left;">Southernmost latitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Greater Cape Floristic Region, South Africa</td>
<td style="text-align: left;">18.0121</td>
<td style="text-align: left;">23.4480</td>
<td style="text-align: left;">-32.1368</td>
<td style="text-align: left;">-34.8096</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>GCMD keywords:</strong> BIOSPHERE &gt; VEGETATION &gt; VEGETATION COVER; BIOSPHERE &gt; VEGETATION &gt; VEGETATION SPECIES; AFRICA &gt; SOUTHERN AFRICA &gt; SOUTH AFRICA; platform FIELD SURVEYS; instrument GPS.</p>
<section id="file-naming-convention" class="level3">
<h3 class="anchored" data-anchor-id="file-naming-convention">File naming convention</h3>
<p><code>bioscape_veg_{level}_{table}_v{YYYYMMDD}.csv</code> and <code>bioscape_veg_spatial_v{YYYYMMDD}.gpkg</code></p>
<ul>
<li><code>level</code> is <code>plot</code> or <code>quadrat</code>.</li>
<li><code>table</code> is <code>summary</code> (one row per location) or <code>species</code> (one row per taxon at that location).</li>
<li><code>YYYYMMDD</code> is the date these version 1 files were written. This submission is v20261002. The vegetation sources are v20241104 and previously released to the team on GitHub. The spatial source is v20261002. Publication at ORNL is version 1. There is no earlier DOI.</li>
</ul>
<p>Names use lowercase letters, numbers, and underscores.</p>
</section>
<section id="file-descriptions" class="level3">
<h3 class="anchored" data-anchor-id="file-descriptions">File descriptions</h3>
<p>The CSV files have one header row. Numeric missing values are <code>-9999</code>. Text missing values are <code>NA</code>. <code>record_id</code> is unique within each CSV.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 35%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">file</th>
<th style="text-align: right;">rows</th>
<th style="text-align: right;">bytes</th>
<th style="text-align: left;">sha256</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">bioscape_veg_plot_summary_v20261002.csv</td>
<td style="text-align: right;">189</td>
<td style="text-align: right;">22006</td>
<td style="text-align: left;">5616bb12963f6ceb35978c0eadc4971296fc40d571ca714e5f52f792d095606e</td>
</tr>
<tr class="even">
<td style="text-align: left;">bioscape_veg_plot_species_v20261002.csv</td>
<td style="text-align: right;">1974</td>
<td style="text-align: right;">207912</td>
<td style="text-align: left;">63d79b3112a0ff0a4e88f46dd8d5b4487d94ba9b60e463fd06b015155e7abba2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bioscape_veg_quadrat_summary_v20261002.csv</td>
<td style="text-align: right;">756</td>
<td style="text-align: right;">162301</td>
<td style="text-align: left;">8269543d656dcbe0716e113c6fb301dd51fe97b969bd39444ede21d653583b01</td>
</tr>
<tr class="even">
<td style="text-align: left;">bioscape_veg_quadrat_species_v20261002.csv</td>
<td style="text-align: right;">4795</td>
<td style="text-align: right;">768295</td>
<td style="text-align: left;">81fc2914fb2bbb0372805af93cbb50755911d55b97bb678161ea597a38db1357</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bioscape_veg_spatial_v20261002.gpkg</td>
<td style="text-align: right;">499</td>
<td style="text-align: right;">2191360</td>
<td style="text-align: left;">ab5696b3c9a0c81c7ebd619de5ece936c6e7dfcd4d4e7442e7191801c046320c</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><strong>Plot summary</strong> (189 rows). One row per surveyed plot. Fractional cover, vegetation height, and soil depth are means of the four quadrants. <code>site_code_plot</code> is unique.</li>
<li><strong>Plot species</strong> (1974 rows). One row per accepted taxon per plot. Live and dead cover are the sum of the quadrant percent covers divided by 4. Counts are sums across quadrants. <code>site_code_plot</code> plus <code>genus_species_combo</code> is unique except where noted in Quality assessment.</li>
<li><strong>Quadrat summary</strong> (756 rows). One row per quadrant. <code>site_code_plot_quadrant</code> is unique. All 189 plots have NE, NW, SE, and SW.</li>
<li><strong>Quadrat species</strong> (4795 rows). One row per taxon recorded in a quadrant, after identical rows were dropped. The plot species file is the aggregate of the source table, not of this file after duplicate removal.</li>
</ul>
<p><strong>Spatial file.</strong> bioscape_veg_spatial_v20261002.gpkg is a GeoPackage in WGS 84 (EPSG:4326). Layers are <code>plot_centers</code>, <code>plot_parking</code>, and <code>plot_polygons</code>.</p>
<ul>
<li><code>plot_centers</code>, 189 points and 189 plot ids. No plot id is repeated. Center ids absent from the plot summary: none. <code>bioscape_plot_id</code> matches <code>plot</code>.</li>
<li><code>plot_parking</code>, 122 points where a vehicle was parked for the survey.</li>
<li><code>plot_polygons</code>, 188 Patches of vegetation the botanists deemed to be representative of the plot (e.g.&nbsp;similar species, post-fire age, soil) that are at least 15 meters in radius and ideally over 50 meters.</li>
</ul>
<p><code>plot_centers</code> attributes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>bioscape_plot_id</td>
<td>Name of the BioSCape plot. Matches <code>plot</code>.</td>
</tr>
<tr class="even">
<td>region</td>
<td>General region where the plot is located.</td>
</tr>
<tr class="odd">
<td>botanist</td>
<td>Name of the botanist who conducted the vegetation survey.</td>
</tr>
<tr class="even">
<td>date_time</td>
<td>Clock time of the GPS measurement, <code>YYYY-MM-DDThh:mm:ss</code>. The source text did not include a timezone.</td>
</tr>
<tr class="odd">
<td>name</td>
<td>Name the botanist gave the plot, kept for provenance.</td>
</tr>
<tr class="even">
<td>plot_note</td>
<td>Notes made by the botanist, kept for provenance.</td>
</tr>
<tr class="odd">
<td>description</td>
<td>Short free-text note.</td>
</tr>
<tr class="even">
<td>quality_flag</td>
<td>Flag assigned by the Townsend team while visiting the plot during BioSCape. Values are listed below.</td>
</tr>
<tr class="odd">
<td>quality_flag_2</td>
<td>A second Townsend visit flag. One plot is <code>Boundary</code>.</td>
</tr>
<tr class="even">
<td>location_flag</td>
<td>The original GPS may not have been taken at the plot center. This flag is set when that plot’s BioSCape center and its own Townsend center differ by more than 10 m. The stored value is <code>See Townsend alternative location</code>. See <code>townsend_long</code> and <code>townsend_lat</code>.</td>
</tr>
<tr class="odd">
<td>pt_plot_a</td>
<td>Townsend opportunistic plot associated with this BioSCape plot. Additional plots were collected where the original plot had a quality flag, where nearby vegetation was similar but had a different dominant species, or where a nearby patch was a single species.</td>
</tr>
<tr class="even">
<td>pt_plot_b</td>
<td>A second Townsend plot label. See <code>pt_plot_a</code>.</td>
</tr>
<tr class="odd">
<td>pt_plot_c</td>
<td>A third Townsend plot label. See <code>pt_plot_a</code>.</td>
</tr>
<tr class="even">
<td>pt_plot_d</td>
<td>A fourth Townsend plot label. See <code>pt_plot_a</code>.</td>
</tr>
<tr class="odd">
<td>townsend_long</td>
<td>Alternative longitude, decimal degrees, of the plot center marked by the Townsend team.</td>
</tr>
<tr class="even">
<td>townsend_lat</td>
<td>Alternative latitude, decimal degrees, of the plot center marked by the Townsend team.</td>
</tr>
<tr class="odd">
<td>geom</td>
<td>Longitude and latitude of the BioSCape plot center.</td>
</tr>
</tbody>
</table>
<p><code>quality_flag</code> values in <code>plot_centers</code>:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">quality_flag</th>
<th style="text-align: right;">Plots</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Low vegetation</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boundary</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trampled</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Accessibility</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Removed invasive</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grazing</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>Boundary</code> means the plot was placed on the boundary of two vegetation types. The Townsend team then set up additional plots nearby to record the distinct communities (<code>pt_plot_a</code> through <code>pt_plot_d</code>). <code>Low vegetation</code> means cover was very low, and an alternative plot was often marked nearby where cover was higher. <code>Trampled</code> means previous visitors had trampled the plot. <code>Removed invasive</code> means a Townsend-team botanist removed an invasive individual that could have been present during the flights. <code>Grazing</code> means there was evidence of grazing. <code>Other</code> and <code>Accessibility</code> are stored on some plots.</p>
<p><code>plot_parking</code> columns are <code>bioscape_plot_id</code>, <code>region</code>, <code>name</code>, <code>description</code>, and <code>date_time</code>. <code>plot_polygons</code> columns are <code>bioscape_plot_id</code>, <code>region</code>, <code>botanist</code>, <code>name</code>, <code>description</code>, and <code>date_time</code>.</p>
<p><strong>Code.</strong> <code>workflow/plot_data_compile_xlsx.R</code> in <a href="https://github.com/BioSCape-io/BioSCape-terrestrial" class="uri">https://github.com/BioSCape-io/BioSCape-terrestrial</a>.</p>
</section>
<section id="data-file-properties" class="level3">
<h3 class="anchored" data-anchor-id="data-file-properties">Data file properties</h3>
<p>Tabular CSV, plus one GeoPackage. The four tables have no map projection. bioscape_veg_spatial_v20261002.gpkg uses geographic WGS 84 (EPSG:4326). Processing level: in situ field observations, with accepted names applied at compilation. These are not a satellite Level 2–4 product.</p>
</section>
<section id="data-details" class="level3">
<h3 class="anchored" data-anchor-id="data-details">Data details</h3>
<p>Shared codes:</p>
<ul>
<li><code>quadrant</code>: NE, NW, SE, SW.</li>
<li><code>clonal</code> and <code>clonal_yes_no</code>: <code>yes</code>, <code>no</code>, or <code>NA</code>.</li>
<li><code>seasonally_apparent</code>: <code>0</code>, <code>1</code>, or <code>-9999</code>.</li>
<li><code>groundwater</code>: Well-drained, Impeded drainage, Seepage, Swamp, Stream bank, Suurvlakte, or <code>NA</code>.</li>
<li><code>sampled</code> on the plot summary is <code>1</code> for every row.</li>
</ul>
<p><strong>bioscape_veg_plot_summary_v20261002.csv</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Units</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>record_id</td>
<td></td>
<td>Unique row number in this file.</td>
</tr>
<tr class="even">
<td>plot</td>
<td></td>
<td>Plot code, <code>T</code> plus three digits. Unique in this file.</td>
</tr>
<tr class="odd">
<td>site_code</td>
<td></td>
<td>Survey area name.</td>
</tr>
<tr class="even">
<td>site_code_plot</td>
<td></td>
<td>Site and plot joined by <code>_</code>. Unique row key.</td>
</tr>
<tr class="odd">
<td>gps_plot_centre</td>
<td></td>
<td>Text note on how the center was recorded. Not a coordinate.</td>
</tr>
<tr class="even">
<td>observer</td>
<td></td>
<td>Botanist named on the field sheet. <code>deb</code> is stored as Douglas Euston-Brown.</td>
</tr>
<tr class="odd">
<td>percent_bare_soil</td>
<td>percent</td>
<td>Mean of the four quadrant estimates. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>percent_bare_rock</td>
<td>percent</td>
<td>Mean of the four quadrant estimates. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>percent_dead_vegetation</td>
<td>percent</td>
<td>Mean of the four quadrant estimates. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>percent_live_vegetation</td>
<td>percent</td>
<td>Mean of the four quadrant estimates. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>veg_height_mean_cm</td>
<td>cm</td>
<td>Mean vegetation height across quadrants. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>soil_depth_cm</td>
<td>cm</td>
<td>Mean soil depth across quadrants. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>groundwater</td>
<td></td>
<td>Drainage class taken from the quadrants.</td>
</tr>
<tr class="even">
<td>access_notes</td>
<td></td>
<td>Free-text access note.</td>
</tr>
<tr class="odd">
<td>sampled</td>
<td></td>
<td>Completed-survey flag. Always 1.</td>
</tr>
</tbody>
</table>
<p>This file has no survey date. Take <code>date</code> from the quadrat summary, joining on <code>plot</code>. Field surveys were recorded by Ross Turner, Douglas Euston-Brown, Steven Molteno, Stuart Hall, and Paul Emms.</p>
<p><strong>bioscape_veg_plot_species_v20261002.csv</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Units</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>record_id</td>
<td></td>
<td>Unique row number in this file.</td>
</tr>
<tr class="even">
<td>plot</td>
<td></td>
<td>Plot code.</td>
</tr>
<tr class="odd">
<td>site_code</td>
<td></td>
<td>Survey area name.</td>
</tr>
<tr class="even">
<td>site_code_plot</td>
<td></td>
<td>Site and plot joined by <code>_</code>.</td>
</tr>
<tr class="odd">
<td>accepted_genus</td>
<td></td>
<td>Accepted genus.</td>
</tr>
<tr class="even">
<td>accepted_species</td>
<td></td>
<td>Accepted species epithet.</td>
</tr>
<tr class="odd">
<td>name_check</td>
<td></td>
<td>Name-check code copied from the field sheet. The list that issued the numbers is not identified in the source workbooks. Missing: <code>NA</code>.</td>
</tr>
<tr class="even">
<td>genus_species_combo</td>
<td></td>
<td>Accepted genus and species as one label.</td>
</tr>
<tr class="odd">
<td>percent_cover_alive</td>
<td>percent</td>
<td>Sum of quadrant live cover, divided by 4. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>percent_cover_dead</td>
<td>percent</td>
<td>Sum of quadrant dead cover, divided by 4. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>abundance_alive_count</td>
<td>count</td>
<td>Sum of live counts across quadrants. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>abundance_dead_count</td>
<td>count</td>
<td>Sum of dead counts across quadrants. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>mean_canopy_diameter_cm</td>
<td>cm</td>
<td>Mean of recorded quadrant canopy diameters. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>clonal</td>
<td></td>
<td><code>yes</code>, <code>no</code>, or <code>NA</code>.</td>
</tr>
<tr class="odd">
<td>seasonally_apparent</td>
<td></td>
<td>Maximum of the quadrant values. Missing: <code>-9999</code>.</td>
</tr>
</tbody>
</table>
<p><strong>bioscape_veg_quadrat_summary_v20261002.csv</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Units</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>record_id</td>
<td></td>
<td>Unique row number in this file.</td>
</tr>
<tr class="even">
<td>plot</td>
<td></td>
<td>Plot code.</td>
</tr>
<tr class="odd">
<td>site_code</td>
<td></td>
<td>Survey area name.</td>
</tr>
<tr class="even">
<td>site_code_plot</td>
<td></td>
<td>Site and plot joined by <code>_</code>.</td>
</tr>
<tr class="odd">
<td>site_code_plot_quadrant</td>
<td></td>
<td>Site, plot, and quadrant joined by <code>_</code>. Unique row key.</td>
</tr>
<tr class="even">
<td>quadrant</td>
<td></td>
<td>NE, NW, SE, or SW.</td>
</tr>
<tr class="odd">
<td>gps_plot_centre</td>
<td></td>
<td>Text note. Not a coordinate.</td>
</tr>
<tr class="even">
<td>observer</td>
<td></td>
<td>Botanist named on the field sheet.</td>
</tr>
<tr class="odd">
<td>date</td>
<td></td>
<td>Survey date, <code>YYYY-MM-DD</code>.</td>
</tr>
<tr class="even">
<td>percent_bare_soil</td>
<td>percent</td>
<td>Quadrant estimate. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>percent_bare_rock</td>
<td>percent</td>
<td>Quadrant estimate. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>percent_dead_vegetation</td>
<td>percent</td>
<td>Quadrant estimate. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>percent_live_vegetation</td>
<td>percent</td>
<td>Quadrant estimate. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>total_cover_check</td>
<td>percent</td>
<td>Sum of the four cover fractions. 14 quadrants are not 100 and are not missing. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>veg_height_cm</td>
<td>cm</td>
<td>Vegetation height. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>post_fire_age_years</td>
<td>text</td>
<td>Time since fire as written on the sheet. The column is text because some entries are notes or Excel date serials rather than ages.</td>
</tr>
<tr class="odd">
<td>soil_depth_cm</td>
<td>cm</td>
<td>Soil depth. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>groundwater</td>
<td></td>
<td>Drainage class.</td>
</tr>
<tr class="odd">
<td>parking_gps</td>
<td></td>
<td>Text note that a parking location was recorded. Not a coordinate.</td>
</tr>
<tr class="even">
<td>access_notes</td>
<td></td>
<td>Free-text access note.</td>
</tr>
<tr class="odd">
<td>comments</td>
<td></td>
<td>Free-text site description.</td>
</tr>
<tr class="even">
<td>sheet_name</td>
<td></td>
<td>Source workbook: Ross01, Ross01b, Ross01c, Bio02, Bio03, or Bio04.</td>
</tr>
<tr class="odd">
<td>old_plot</td>
<td></td>
<td>Plot number before the Swartberg renumbering in Methods. Missing: <code>-9999</code>.</td>
</tr>
</tbody>
</table>
<p><strong>bioscape_veg_quadrat_species_v20261002.csv</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Units</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>record_id</td>
<td></td>
<td>Unique row number in this file.</td>
</tr>
<tr class="even">
<td>plot</td>
<td></td>
<td>Plot code.</td>
</tr>
<tr class="odd">
<td>site_code</td>
<td></td>
<td>Survey area name.</td>
</tr>
<tr class="even">
<td>site_code_plot</td>
<td></td>
<td>Site and plot joined by <code>_</code>.</td>
</tr>
<tr class="odd">
<td>site_code_plot_quadrant</td>
<td></td>
<td>Site, plot, and quadrant joined by <code>_</code>.</td>
</tr>
<tr class="even">
<td>quadrant</td>
<td></td>
<td>NE, NW, SE, or SW.</td>
</tr>
<tr class="odd">
<td>accepted_genus</td>
<td></td>
<td>Accepted genus.</td>
</tr>
<tr class="even">
<td>accepted_species</td>
<td></td>
<td>Accepted species epithet. <code>NA</code> when the record is genus only.</td>
</tr>
<tr class="odd">
<td>subspecies_or_variant</td>
<td></td>
<td>Subspecies or variant when one was recorded.</td>
</tr>
<tr class="even">
<td>genus_species_combo</td>
<td></td>
<td>Genus and species label.</td>
</tr>
<tr class="odd">
<td>name_check</td>
<td></td>
<td>Name-check code. <code>NA</code> on 167 of 4795 rows.</td>
</tr>
<tr class="even">
<td>new_species</td>
<td></td>
<td>Field note for a new or uncertain taxon. URLs were removed. Remaining values can be notes or times.</td>
</tr>
<tr class="odd">
<td>clonal_yes_no</td>
<td></td>
<td><code>yes</code>, <code>no</code>, or <code>NA</code>.</td>
</tr>
<tr class="even">
<td>mean_canopy_diameter_cm</td>
<td>cm</td>
<td>Canopy diameter of the taxon in the quadrant. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>abundance_alive_count</td>
<td>count</td>
<td>Live individuals. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>percent_cover_alive</td>
<td>percent</td>
<td>Live cover in the quadrant. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>percent_cover_dead</td>
<td>percent</td>
<td>Dead cover in the quadrant. Missing: <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>abundance_dead_count</td>
<td>count</td>
<td>Dead individuals. Missing: <code>-9999</code>.</td>
</tr>
<tr class="odd">
<td>seasonally_apparent</td>
<td></td>
<td><code>0</code>, <code>1</code>, or <code>-9999</code>.</td>
</tr>
<tr class="even">
<td>comment</td>
<td></td>
<td>Note on the taxon in that quadrant.</td>
</tr>
<tr class="odd">
<td>clonal</td>
<td></td>
<td><code>yes</code>, <code>no</code>, or <code>NA</code>.</td>
</tr>
<tr class="even">
<td>taxon</td>
<td></td>
<td>Same label as <code>genus_species_combo</code>.</td>
</tr>
<tr class="odd">
<td>old_plot</td>
<td></td>
<td>Plot number before Swartberg renumbering. Missing: <code>-9999</code>.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="application-and-derivation" class="level2">
<h2 class="anchored" data-anchor-id="application-and-derivation">Application and derivation</h2>
<p>These plots are the environmentally stratified vegetation surveys for BioSCape. They are the ground observations for comparing field composition and structure with the campaign airborne imaging spectroscopy and lidar (AVIRIS-NG, PRISM, LVIS, and HyTES) over the Greater Cape Floristic Region (Cardoso et al.&nbsp;2025). Use the plot species table for one cover and count per taxon per plot. Use the quadrat tables when the within-plot measurements matter. The woody-invasive plots (ORNL DAAC <a href="https://doi.org/10.3334/ORNLDAAC/2511" class="uri">https://doi.org/10.3334/ORNLDAAC/2511</a>) were sited near this network and are comparable only after that placement difference is taken into account.</p>
</section>
<section id="quality-assessment" class="level2">
<h2 class="anchored" data-anchor-id="quality-assessment">Quality assessment</h2>
<p>Cover fractions are visual estimates. This version does not add an uncertainty column. <code>total_cover_check</code> is the field sum of bare soil, bare rock, dead vegetation, and live vegetation. Quadrants that do not sum to 100:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">site_code_plot_quadrant</th>
<th style="text-align: right;">total_cover_check</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">capepoint_T070_NE</td>
<td style="text-align: right;">104</td>
</tr>
<tr class="even">
<td style="text-align: left;">capepoint_T070_NW</td>
<td style="text-align: right;">105</td>
</tr>
<tr class="odd">
<td style="text-align: left;">capepoint_T070_SE</td>
<td style="text-align: right;">102</td>
</tr>
<tr class="even">
<td style="text-align: left;">capepoint_T070_SW</td>
<td style="text-align: right;">105</td>
</tr>
<tr class="odd">
<td style="text-align: left;">capepoint_T265_NE</td>
<td style="text-align: right;">120</td>
</tr>
<tr class="even">
<td style="text-align: left;">capepoint_T265_NW</td>
<td style="text-align: right;">130</td>
</tr>
<tr class="odd">
<td style="text-align: left;">capepoint_T265_SE</td>
<td style="text-align: right;">150</td>
</tr>
<tr class="even">
<td style="text-align: left;">capepoint_T265_SW</td>
<td style="text-align: right;">140</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gardenroute_T148_SW</td>
<td style="text-align: right;">101</td>
</tr>
<tr class="even">
<td style="text-align: left;">langeberg_T117_NE</td>
<td style="text-align: right;">107</td>
</tr>
<tr class="odd">
<td style="text-align: left;">langeberg_T117_NW</td>
<td style="text-align: right;">105</td>
</tr>
<tr class="even">
<td style="text-align: left;">outeniqua_T261_NW</td>
<td style="text-align: right;">90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rooiberg_T003_SW</td>
<td style="text-align: right;">103</td>
</tr>
<tr class="even">
<td style="text-align: left;">swartberg_T026_NW</td>
<td style="text-align: right;">115</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Version 1 changes from the source tables:</p>
<ul>
<li>Site codes on 12 plots in the species tables were replaced with the plot-summary spelling so <code>site_code_plot</code> joins.</li>
<li>1 identical quadrat-species rows were removed.</li>
<li>1 web address in <code>new_species</code> was removed.</li>
<li>The observer value <code>deb</code> and the spatial botanist name <code>Doug Euston-Brown</code> are stored as Douglas Euston-Brown.</li>
<li>Spatial source v20261002 drops the duplicate T114 center and its location flag, sets T074 region to <code>CapePoint</code>, links T183 to associated plot <code>pt183</code>, stores <code>pt_plot_d</code> as one column, and uses real missing values instead of the text <code>NA</code> in Townsend plot labels.</li>
</ul>
<p>13 quadrat-by-taxon keys still occur more than once because the cover or count differed. <code>record_id</code> keeps those rows distinct. The plot species file was summed from the source table, so those repeated measurements are included in its cover and counts.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">site_code_plot_quadrant</th>
<th style="text-align: left;">genus_species_combo</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">anysberg_T106_SE</td>
<td style="text-align: left;">Elytropappus rhinocerotis</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">anysberg_T108_NW</td>
<td style="text-align: left;">Ruschia pungens</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cederberg_T243_SW</td>
<td style="text-align: left;">Anthospermum aethiopicum</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">dehoop_T132_NE</td>
<td style="text-align: left;">Pterocelastrus tricuspidatus</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gardenroute_T147_NE</td>
<td style="text-align: left;">Helichrysum patulum</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">gardenroute_T147_NW</td>
<td style="text-align: left;">Helichrysum patulum</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gardenroute_T147_SE</td>
<td style="text-align: left;">Helichrysum patulum</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">gardenroute_T147_SW</td>
<td style="text-align: left;">Helichrysum patulum</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">langeberg_T186_SE</td>
<td style="text-align: left;">Erica anguliger</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">langeberg_T186_SE</td>
<td style="text-align: left;">Penaea mucronata</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">outeniqua_T185_SE</td>
<td style="text-align: left;">Protea neriifolia</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">rooiberg_T003_SW</td>
<td style="text-align: left;">Drosanthemum</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rooiberg_T245_SW</td>
<td style="text-align: left;">Agathosma mundtii</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>post_fire_age_years</code> remains text. <code>name_check</code> is the code written on the field sheet; the authority list is not in these tables.</p>
</section>
<section id="data-acquisition-materials-and-methods" class="level2">
<h2 class="anchored" data-anchor-id="data-acquisition-materials-and-methods">Data acquisition, materials, and methods</h2>
<p>Plots were placed across reserves and passes in the Greater Cape Floristic Region for the 2023 BioSCape field campaign (Cardoso et al. 2025). Each surveyed plot has four quadrants: NE, NW, SE, and SW. In each quadrant the botanist recorded fractional cover of bare soil, bare rock, dead vegetation, and live vegetation; vegetation height; soil depth; drainage; and, for each vascular plant taxon, live and dead percent cover, live and dead counts, and canopy diameter. Centers were located with a Trimble GPS. The coordinate values are in the <code>plot_centers</code> layer of bioscape_veg_spatial_v20261002.gpkg.</p>
<p>The version 1 files were written by this document. Column names are snake case. Numeric gaps are <code>-9999</code> and text gaps are <code>NA</code>. Survey dates are <code>YYYY-MM-DD</code>. GPS times are <code>YYYY-MM-DDThh:mm:ss</code> with the clock time taken from the source string. Each CSV has <code>record_id</code>. Clonal codes are <code>yes</code> or <code>no</code>. <code>old_plot</code> is the plot number before renumbering.</p>
<p>Field records were kept in six Google Sheets workbooks (Ross01, Ross01b, Ross01c, Bio02, Bio03, Bio04) and downloaded on 2024-11-04. <code>workflow/plot_data_compile_xlsx.R</code> stacked the SiteData tabs and the plot tabs, and rebuilt the plot and quadrant identifiers. Swartberg plot numbers that collided with numbers used at other sites were renumbered. The previous number is <code>old_plot</code>. The source script maps Swartberg 20 to T110, 22 to T012, 23 to T013, and 24 to T014.</p>
<p>Plot summary cover, height, and soil depth are the mean of the four quadrants. Plot species live and dead cover are the sum of that taxon’s quadrant covers divided by 4, and counts are sums. Unrecorded quadrant occurrences add nothing to the sum. With four quadrants in every released plot, dividing by 4 is that taxon’s mean contribution to the plot.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Cardoso, A.W., E.L. Hestir, J.A. Slingsby, C.J. Forbes, G.R. Moncrieff, W. Turner, A.L. Skowno, J. Nesslage, P.G. Brodrick, K.D. Gaddis, and A.M. Wilson. 2025. The biodiversity survey of the Cape (BioSCape), integrating remote sensing with biodiversity science. <em>npj Biodiversity</em> 4:2. <a href="https://doi.org/10.1038/s44185-024-00071-5" class="uri">https://doi.org/10.1038/s44185-024-00071-5</a></p>
<p>Fitzpatrick, M.C., D. Spalink, A.J. Elmore, J. Measey, and S. Kritzinger-Klopper. 2026. BioSCape: Vegetation Composition at Plots with Woody Invasives, CFR, South Africa. ORNL DAAC, Oak Ridge, Tennessee, USA. <a href="https://doi.org/10.3334/ORNLDAAC/2511" class="uri">https://doi.org/10.3334/ORNLDAAC/2511</a></p>
<p>Slimp, M., J. Malindi, R. Meyer, A. Cunningham, J. Rourke, M. Hayden, A. Hargey, J. Nesslage, S. Johnson, M. Rossi, and N. Stavros. 2025. BioSCape Vegetation Surveys Berg and Eerste River Catchments, South Africa, 2022–2023. ORNL DAAC, Oak Ridge, Tennessee, USA. <a href="https://doi.org/10.3334/ORNLDAAC/2425" class="uri">https://doi.org/10.3334/ORNLDAAC/2425</a></p>
</section>
<section id="dataset-revisions" class="level2">
<h2 class="anchored" data-anchor-id="dataset-revisions">Dataset revisions</h2>
<p>This release is compiled from v20241104 vegetation tables and the v20261002 spatial GeoPackage from the team GitHub repository. It was updated to conform to ORNL data standards as v20261002. This is the first submission of these tables to ORNL DAAC. There is no prior DOI.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/BioSCape-io\.github\.io\/BioSCape-terrestrial\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>