on:
  push:
    branches: main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 1 * * *'

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      # add software dependencies here

      # To publish to Netlify, RStudio Connect, or GitHub Pages, uncomment
      # the appropriate block below
      - name: Install R Package Dependencies
        run: |-
          Rscript -e "install.packages('questionr')"
          Rscript -e "questionr::qscan(list.files(pattern='*.qmd',recursive=T), load = TRUE, detail = FALSE)" # this scans all scripts and installs any needed packages

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      
