on:
  push:
    branches: main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 1 * * *'

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    container: adamwilsonlab/emma:latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install R Package Dependencies
        run: |-
          sudo apt-get install  libcurl4-openssl-dev
          Rscript -e "install.packages('questionr')"
          Rscript -e "install.packages('curl')"
          Rscript -e "install.packages('gargle')"
          Rscript -e "install.packages('tidyverse')"
          Rscript -e "install.packages('googledrive')"
          Rscript -e "install.packages('httr')"
          Rscript -e "install.packages('googlesheets4')"
          Rscript -e "install.packages('rmarkdown')"
          Rscript -e "questionr::qscan(list.files(pattern='*.qmd',recursive=T), load = TRUE, detail = FALSE)" # this scans all scripts and installs any needed packages
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      
