on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: adamwilsonlab/emma:latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::httr
            any::tidyverse
            any::googlesheets4
            any::rmarkdown
      - name: Install others not mentioned
        run: |-
          Rscript -e "questionr::qscan(list.files(pattern='*.qmd',recursive=T), load = TRUE, detail = FALSE)" # this scans all scripts and installs any needed packages
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}